let shopItemsData = [
    {
    id:"item1",
    name:"The Stranger",
    price:"15",
    desc:"ALBERT CAMUS",
    authorLink: "Albert.html",
    desc2:"life has no purpose that death is the only certainty in life and...",
    img:"imges/617WkdpG8xL._SY522_.jpg",
 },
 {
     id:"item2",
     name:"Metamorphosis",
     price:"9",
     desc:"FRANZ KAFKA",
     authorLink: "franz kafka.html",
     desc2:"Why You Cant Trust Good People...",
     img:"imges/61pMBc1z5SS._SY522_.jpg",
 },
 {
     id:"item3",
     name:"The Ball Jar",
     price:"11",
     desc:"SYLVIA PLATH",
     authorLink: "Sylvia Plath.html",
     desc2:"details the life of Esther Greenwood, a college student who dreams...",
     img:"imges/Sylvia Plath.jfif",
 },
 {
     id:"item4",
     name:"Death on the Nile",
     price:"18",
     desc:"AGHATA CHIRISTI",
     authorLink: "Agatha Christie.html",
     desc2:"Hercule Poirot Egyptian adventure aboard a glamorous river steamer...",
     img:"imges/Death on the Nile _ Christie, Agatha, 1890-1976, author _ Free Download, Borrow, and Streaming _ Internet Archive.jfif",
 },
 {
     id:"item5",
     name:"The picture of dorian Gray",
     price:"16",
     desc:"OSCAR WILDE",
     authorLink: "oscar wilde.html",
     desc2:"a young man who purchases eternal youth at the expense of his soul...",
     img:"imges/download (8).jfif",
 },
 {
     id:"item6",
     name:"Ariel",
     price:" 15",
     desc:"SYLVIA PLATH",
     authorLink: "Sylvia Plath.html",
     desc2:" a book of poems dominated by the idea of death, suicide and sadness...",
     img:"imges/Sylvia Plath, Ariel.jfif",
 },
 {
     id:"item7",
     name:"The Idiot",
     price:"31",
     desc:"FYODOR SODTOEVSKY",
     authorLink: "dostoveskey.html",
     desc2:"Prince Lev Myshkin as he arrives in a corrupt St. Petersburg and...",
     img:" imges/71p1tvi1XgS._SY522_.jpg",
 },
 {
     id:"item8",
     name:"White Nights",
     price:"18 ",
     desc:"FYODOR SODTOEVSKY",
     authorLink: "dostoveskey.html",
     desc2:"the essence of isolation and the yearning for human connection...",
     img:" imges/41hykoV3d-L._SY522_.jpg",
 },
 {
     id:"item9",
     name:"Crime and Punishment",
     price:"13",
     desc:"FYODOR SODTOEVSKY",
     authorLink: "dostoveskey.html",
     desc2:"Raskolnikov, an impoverished student tormented by his own nihilism...",
     img:" imges/81bAXZAp-GL._SL1500_.jpg",
 },
 {
     id:"item11",
     name:"Towards Zero",
     price:"18",
     desc:"AGHATA CHIRISTI",
     authorLink: "Agatha Christie.html",
     desc2:"An elderly widow is murdered at a clifftop seaside house...",
     img:" imges/81w7kGazeLL._SL1500_.jpg ",
 },
 {
     id:"item10",
     name:"The Picture of Dorian Gray",    
      price:"12",
     desc:"OSCAR WILDE",
     authorLink: "oscar wilde.html",
     desc2:"a young man who purchases eternal youth at the expense of...",
     img:"imges/61FdXlJX0-L._SY522_.jpg",
 },
 {
     id:"item12",
     name:"Letter To Milena",
     price:"19",
     desc:"FRANZ KAFKA",
     authorLink: "franz kafka.html",
     desc2:"Kafka delves into themes of existential angst, expressing his...",
     img:" imges/71NxaDZFDSL._SL1500_.jpg",
 },
 {
     id:"item13",
     name:"Anna Karenina",
     price:"29",
     desc:"LEO TOLSTOY",
     authorLink: "Leo Tolstoy.html",
     desc2:" the adulterous affair between Anna, wife of Aleksey Karenin...",
     img:"imges/img.10.jpg ",
 },
 {
     id:"item14",
     name:"Anna Karénine  ",
     price:"18",
     desc:"the adulterous affair between Anna, wife of Aleksey Karenin...",
     authorLink: "Leo Tolstoy.html",
     desc2:"LEO TOLSTOY",
     img:" imges/img.11.jpg",
 },
 {
     id:"item15",
     name:"Les adorables étrangetés",
     price:"12",
     desc:"LEO TOLSTOY",
     authorLink: "Leo Tolstoy.html",
     desc2:"Et puis, un matin, notre première pensée ne nous appartient...",
     img:" imges/img.12.jpg",
 },
 {
     id:"item16",
     name:"The Canterville Ghost",
     price:"19",
     desc:"OSCAR WILDE",
     authorLink: "oscar wilde.html",
     desc2:"s the relationship between an artist or a performer and...",
     img:"imges/The Canterville Ghost ebook by Oscar Wilde - Rakuten Kobo.jfif ",
 },
 {
    id:"item17",
    name:"Keywords for Astrology",
    price:"25.5 ",
    desc:"AGHATA CHIRISTI",
    authorLink: "Agatha Christie.html",
    desc2:"The Essential Guide to Correspondences and Interpretation...",
    img:"imges/keywordsfor....jpg ",

 },
 {
    id:"item18",
    name:"J'ai un ange qui me tient la main",
    price:"15.77 ",
    desc:"Leo Tolstoy",
    authorLink: "Leo Tolstoy.html",
    desc2:"Ils disent que tu n'es pas vraiment partie...",
    img:" imges/img.13.jpg",

 },
 {
    id:"item19",
    name:"The Canterville Ghost ebook",
    price:"13.99",
    desc:"Oscar Wilde",
    authorLink: "oscar wilde.html",
    desc2:"An amusing chronicle of the tribulations ...",
    img:"imges/The Canterville Ghost ebook by Oscar Wilde - Rakuten Kobo.jfif ",

 },
 {
    id:"item20",
    name:"The Man in the Brown Suit",
    price:"17.60 ",
    desc:"Agatha Christie",
    authorLink: "Agatha Christie.html",
    desc2:"Newly-orphaned Anne Beddingfield is a lovely...",
    img:" imges/71y8QomsLaL._SL1500_.jpg",

 },
 {
    id:"item21",
    name:"La Chute",
    price:"28 ",
    desc:"Albert CAMUS",
    authorLink: "Albert.html",
    desc2:" Sur le pont, je passai derrière une forme penchée...",
    img:"imges/La Chute.jpg",
 },
 {
    id:"item22",
    name:"Mille soleils splendides",
    price:" 19.2",
    desc:"Khaled Hosseini",
    authorLink: "khalid Housseni.html",
    desc2:"À Kaboul, Mariam endure un mariage contraint avec un...",
    img:"imges/miile soleils splendides.img ",
 },
 {
    id:"item23",
    name:"Sylvia Plath Poems",
    price:"10 ",
    desc:"Sylvia Plath",
    authorLink: "Sylvia Plath.html",
    desc2:"To my knowledge, she never scrapped any of her poetic...",
    img:" imges/Sylvia Plath Poems Chosen by Carol Ann Duffy.jfif",
 },
 {
    id:"item24",
    name:"LA Peste",
    price:" 22.20",
    desc:"Albert Camus",
    authorLink: "Albert.html",
    desc2:"It's a powerful and thought-provoking work that explores...",
    img:"imges/la peste.jpg ",
 },
 {
    id:"item25",
    name:"Letter to The Father",
    price:"14.5 ",
    desc:">Franz Kafka’s",
    authorLink: "franz kafka.html",
    desc2:"A son’s poignant letter to his father—from the ...",
    img:"imges/51g4YIeDx1L._SL1200_.jpg ",
 },
 {
    id:"item26",
    name:"THE KITE RUNNER",
    price:"17 ",
    desc:"Khaled Housseni",
    authorLink: "khalid Housseni.html",
    desc2:"A vivid and engaging story that reminds us how long...",
    img:"imges/BOOK REVIEW _ THE KITE RUNNER BY KHALED HOSSEINI.jfif ",
 },
 {
    id:"item27",
    name:"Sea Prayer",
    price:"19.99",
    desc:"Khaled Housseni",
    authorLink: "khalid Housseni.html",
    desc2:"Hosseini's story, aimed at readers of all ages...",
    img:"imges/Sea Prayer, Khaled Hosseini.jfif ",
 },
 {
    id:"item28",
    name:"L'étranger",
    price:"20",
    desc:"Albert Camus",
    authorLink: "Albert.html",
    desc2:" Its theme and outlook are often cited as examples...",
    img:"imges/L'étranger.jpg ",
 },
 {
    id:"item29",
    name:"The Letters of Sylvia Plath",
    price:" 55.80",
    desc:"Sylvia Plath",
    authorLink: "Sylvia Plath.html",
    desc2:"One of the most beloved poets of the modern age...",
    img:" imges/9780062740434.webp",
 },
 {
    id:"item30",
    name:"Romeo y Julieta ",
    price:"15 ",
    desc:"Oscar Wilde",
    authorLink: "oscar wilde.html",
    desc2:"Romeo y Julieta es la historia de un amor que...",
    img:"imges/9781985248113.jpg ",
 },
 {
    id:"item31",
    name:"Resurrection",
    price:"15.74 ",
    desc:"Leo Tolstoy",
    authorLink: "Leo Tolstoy.html",
    desc2:"the last of Tolstoy's major novels, tells the story...",
    img:"imges/9780199555765.jpg ",
 },
 {
    id:"item32",
    name:"The Uncensored Picture of Dorian Gray",
    price:"18.50 ",
    desc:"Oscar Wilde",
    authorLink: "oscar wilde.html",
    desc2:"More than 120 years after Oscar Wilde submitted...",
    img:" imges/9780674066311.jpg",
 },

 
 
 ];